spring:
  datasource:
      url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimzon=UTC
      username: root
      password: password
  flyway:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimzon=UTC
    user: root
    password: password
    baseline-on-migrate: true
    schemas: my_db

